import type { Metadata } from "next";
import { Inter,Ubuntu ,Roboto_Mono} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/modules/Common/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})
const ubuntu = Ubuntu({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400','500','700'],
})

export const metadata: Metadata = {
  title: "Teams Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <body className={ubuntu.className}>

          {children}
          <Toaster richColors />
      </body>
    </html>
  );
}
